import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const myFont = localFont({
  src: "fonts/Helvetica.woff",
});

const helvetica = localFont({
  src: [
    {
      path: "/fonts/helvetica-light-587ebe5a59211.woff",
      weight: "300", // Light weight
      style: "normal",
    },
    {
      path: "/fonts/Helvetica.woff",
      weight: "400", // Normal weight
      style: "normal",
    },

    {
      path: "/fonts/Helvetica-Bold.woff",
      weight: "700", // Bold weight
      style: "normal",
    },
    {
      path: "/fonts/Helvetica-BoldOblique.woff",
      weight: "700", // Bold weight, oblique style
      style: "oblique",
    },
  ],
  display: "swap",
  variable: "--font-helvetica", // Define the CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={helvetica.className}>
      <body>{children}</body>
    </html>
  );
}
